ListView tests
openedx/frontend-app-ora-grading pull request #12
Opened 2021-10-08 15:00 UTC by muselesscreator

Add tests for ListView component.

Split out the TableControls for ease of mocking.

moved url designations to `data/services/lms/urls`

JIRA: [AU-331](https://openedx.atlassian.net/browse/AU-331)

2021-10-18 20:24 UTC, leangseu-edx commented on src/containers/ListView/TableControls.test.jsx
> +    TableController: () => 'DataTable.TableController',
TableControlBar
```suggestion
    TableControlBar: () => 'DataTable.TableControlBar',
```

2021-10-18 20:27 UTC, leangseu-edx requested changes
Change the typo and update the snapshot

2021-10-19 13:11 UTC, muselesscreator commented
> Change the typo and update the snapshot

good catch and thx.  done :-)

2021-10-19 13:12 UTC, leangseu-edx approved these changes
LGTM 👍

2021-10-19 13:29 UTC, merged