file submisson display
openedx/frontend-app-ora-grading pull request #16
Opened 2021-10-25 17:08 UTC by leangseu-edx

Ticket: [AU-373](https://openedx.atlassian.net/browse/AU-373)

What changed:
- Small refactor because it was quite messy
- Update a small fix to a snapshot test
- Implement the display for submission file

AC:
- [x] display submission files
- [x] Unit testing
- [x] Make it responsive

### No files
![no-files](https://user-images.githubusercontent.com/83240113/138739764-f6df5ae4-c3ea-49f4-ba53-1e4535872acb.png)
![Screen Shot 2021-10-25 at 2 25 40 PM](https://user-images.githubusercontent.com/83240113/138749878-e92c5c1d-5247-4609-8fdd-26533bd80890.png)

### File expand
![file-expand](https://user-images.githubusercontent.com/83240113/138739763-602d89e4-e746-425a-9056-0bf79d5124bf.png)
![Screen Shot 2021-10-25 at 2 25 31 PM](https://user-images.githubusercontent.com/83240113/138749910-bac9716f-d99e-4b50-8c08-2233a6e9077b.png)

### File Collapsed
![file-collapse](https://user-images.githubusercontent.com/83240113/138739761-dcfc7b13-2ab4-4694-abc5-bc83b0cd830e.png)
![Screen Shot 2021-10-25 at 2 25 52 PM](https://user-images.githubusercontent.com/83240113/138749929-81da5480-2e67-44b2-a072-fcc9ede26964.png)

2021-10-26 21:33 UTC, muselesscreator requested changes
Looks great so far, but added some notes.
Loving the nested component snapshots though!  I wanna find some way for us to clean up the specification of those, but this is a lovely step forward for our snapshots :-)

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/ResponseDisplay.scss
> +      &.disabled {
I do not believe we are intending to disable this.

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +          <h3>Attached Files ({files.length})</h3>
Text should be `File Submissions (<>)`

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +        <h3>No Attached Files Founded</h3>
Text should be `File submissions (0)` and should not be disabled.

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +                Header: 'Download',
No download functionality for this version

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +        <div className="submission-files-footer">
No download functionality for this version

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.test.jsx
> +  Download: () => 'Download', ArrowDropDown: () => 'ArrowDropDown', ArrowDropUp: () => 'ArrowDropUp',
line breaks, and mocked icons work better as strings when used in props.
```suggestion
  Download: 'Download',
  ArrowDropDown: 'ArrowDropDown',
  ArrowDropUp: 'ArrowDropUp',
```

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.test.jsx
> +  const Collapsible = () => 'Collapsible';
don't need to mock top-level Collapsible, as is never used.

I would also inline the simple-components in the return statement to avoid un-necessary repeated lines

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.test.jsx
> +  DataTable.Table = 'DataTable.Table';
But the fact that this works is lovely!

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +                Cell: ({ value }) => (
Please define these as class methods so they can be mocked/tested (sorry this means the component has to become a class)

2021-10-26 21:33 UTC, muselesscreator commented on src/containers/ResponseDisplay/index.test.jsx
> +    });
plz add test for output of the textContent.  Can be by checking the getter or by examining the shallow render.

2021-10-26 21:33 UTC, muselesscreator commented on src/data/services/lms/fakeData/submissionFull.js
> +  const length = parseInt(submissionId.split('-')[1], 10) % fileTypes.length;
I feel like it would be easier/more reasonable here to pre-bake a set of files, and just have the description call out where they are from, if anything baking the submissionId into the name.

Also, I try to avoid the `new Array().fill().map()` trick as it is hard to read, for all that it is nice and effective.

```
const allFiles = [
  'presentation.pdf',
  'example.jpg',
  'diagram.png',
  'notes.doc',
  'recording.wav',
];
const index = parseInt(submissionId.split('-')[1], 10);
const numFiles = index % allFiles.length.
const files = [];
for (var i = 0; i < numFiles; i++) {
  const fileName = `${submissionId}_${allFiles[i]}`;
  files.push({
    name: fileName,
    description: descriptiveText(fileName),
    downloadUrl: `/download/${fileName}/`,
  });
}
return files;
```

2021-10-27 14:24 UTC, leangseu-edx commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +                Header: 'Download',
I thought this would help Gab visual what it look like for individual download look like.

2021-10-27 16:42 UTC, leangseu-edx commented on src/containers/ResponseDisplay/SubmissionFiles.jsx
> +                Cell: ({ value }) => (
Alternative to having it as class, I will write `export const HeaderCell = ({value}) => ...` and use that component to test. It is a component anyway.

2021-10-28 14:08 UTC, muselesscreator commented on src/containers/ResponseDisplay/__snapshots__/SubmissionFiles.test.jsx.snap
> +          src={[Function]}
mock icons as name for snapshots :-p

2021-10-28 14:08 UTC, muselesscreator commented on src/containers/ResponseDisplay/__snapshots__/SubmissionFiles.test.jsx.snap
> +              "Cell": [Function],
mock the header cell function for the snapshots :-p

2021-10-28 15:35 UTC, muselesscreator commented on src/containers/ResponseDisplay/SubmissionFiles.test.jsx
> +        el.instance().renderHeaderEllipsesCell = jest.fn().mockName('HeaderEllipsesCell');
++

2021-10-28 15:35 UTC, muselesscreator approved these changes
Thanks for the updates!

2021-10-29 15:01 UTC, merged