feat problem steps detail UI
openedx/frontend-app-ora-grading pull request #263
Opened 2023-10-09 14:17 UTC by johnvente

2023-10-09 14:17 UTC, openedx-webhooks commented
Thanks for the pull request, @johnvente!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-10-20 16:27 UTC, e0d commented
@johnvente noting that there are some check failures and conflicts that need attention.  Also, note that this is still marked draft and the title says not to review.

2023-11-16 21:47 UTC, mariajgrimaldi requested changes

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ListView/SubmissionsTable.jsx
> +};
what does this mean? problem steps enabled?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ListView/SubmissionsTable.jsx
> +    <Hyperlink destination="#" showLaunchIcon={false}>
why is the destination "#"?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Submission date',
why are we changing `Learner submission date` for `Submission date`?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Problem Steps',
```suggestion
    defaultMessage: 'Problem steps',
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/ReviewProblemStepsContent.jsx
> + */
why is this comment useful?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/CloseReviewConfirmModal.jsx
> +  // injected
is this comment needed?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepActions/messages.js
> +    defaultMessage: 'Problem Steps',
```suggestion
    defaultMessage: 'Problem steps',
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +    <Hyperlink destination="#" showLaunchIcon={false}>
[curious] same question here

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +        status={value !== 'Peers' ? 'graded' : 'ungraded'}
why is the badge graded when the value is not peers?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +            accessor: 'userName',
why is userName instead of username?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +      userName: PropTypes.string.isRequired,
^ same question here

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/messages.js
> +    defaultMessage: 'ID Assessment',
what about Assessment ID? So it matches the other labels

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/messages.js
> +    description: 'ORA Grading ID Assessment column title',
Same comment here about Assessment ID

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/OverrideGradeConfirmModal.jsx
> +  // injected
Same question here

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/ResponsesList/messages.js
> +    defaultMessage: 'Hide Rubric',
```suggestion
    defaultMessage: 'Hide rubric',
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/ResponsesList/messages.js
> +    defaultMessage: 'Show Rubric',
```suggestion
    defaultMessage: 'Show rubric',
```
If we use capitalization elsewhere then we should do it here, but if we don't then we should keep it that way for consistency

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/StopGradingConfirmModal.jsx
> +export default injectIntl(StopGradingConfirmModal);
is it necessary to create a component for each modal?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/messages.js
> +    defaultMessage: 'Are you sure you want to stop grade override?',
```suggestion
    defaultMessage: 'Are you sure you want to stop the grade override?',
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/messages.js
> +  responseListMessageError: {
why do we need multiple messages for the same error?

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/utils.js
> +export const responsesListFormat = (arr = []) => {
```suggestion
export const responsesListFormat = (responses = []) => {
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/index.jsx
> + */
Same comment here ^

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/messages.js
> +    defaultMessage: 'Grading Demo',
```suggestion
    defaultMessage: 'Grading demo',
```

2023-11-16 21:47 UTC, mariajgrimaldi commented on src/data/redux/thunkActions/grading.js
> + * @param {string} submissionUUIDParam - to set an expecifict submission ID to load
should we use this kind of documentation for the modules we're adding?

2023-12-26 21:22 UTC, johnvente commented on src/containers/ListView/SubmissionsTable.jsx
> +    <Hyperlink destination="#" showLaunchIcon={false}>
Because it's a link but won't redirect to any destination

2023-12-26 21:30 UTC, johnvente commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Problem Steps',
These titles are columns in the table they should be in capitalize

2023-12-26 21:30 UTC, johnvente commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +            accessor: 'userName',
The backend gives the data that way

2023-12-26 21:33 UTC, johnvente commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/StopGradingConfirmModal.jsx
> +export default injectIntl(StopGradingConfirmModal);
I wouldn't create only one modal and then use all in one, we should have single modal by feature if were a change for that use case we should change it in one place

2023-12-26 21:36 UTC, johnvente commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/index.jsx
> +        status={value !== 'Peers' ? 'graded' : 'ungraded'}
The mockup for the view was like that, it's only by UI purposes

2023-12-26 21:37 UTC, johnvente commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/messages.js
> +  responseListMessageError: {
We do not need the same error message, I did not know which one to use here they should be different

2023-12-26 21:38 UTC, johnvente commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Submission date',
It was a request in the view by @juancamilom

2023-12-26 21:38 UTC, johnvente commented on src/containers/ListView/SubmissionsTable.jsx
> +};
Yep, it does

2023-12-26 21:46 UTC, johnvente commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/components/AssessmentsTable/messages.js
> +    defaultMessage: 'ID Assessment',
The [figma](https://www.figma.com/proto/dbUxY1HO4OoPtzxxyae1Xe/Status-progress-table-for-course-staff?type=design&node-id=43-1616&t=s7E27UO7p0G8FoEV-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=17%3A5207) doesn't use that label

2024-02-13 15:01 UTC, mariajgrimaldi commented on src/containers/ListView/SubmissionsTable.jsx
> +};
Good! Thanks

2024-02-13 15:01 UTC, mariajgrimaldi commented on src/containers/ListView/SubmissionsTable.jsx
> +    <Hyperlink destination="#" showLaunchIcon={false}>
Oh! Thank you

2024-02-13 15:02 UTC, mariajgrimaldi commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Submission date',
So it got through product review. Thanks.

2024-02-13 15:02 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/components/ReviewProblemStepsContent/messages.js
> +  responseListMessageError: {
Should we ask internally?

2024-02-13 15:03 UTC, mariajgrimaldi commented on src/containers/ReviewProblemStepsModal/messages.js
> +    defaultMessage: 'Grading Demo',
Dismiss comment in favor of: https://github.com/openedx/frontend-app-ora-grading/pull/263#discussion_r1436620251

2024-02-13 15:03 UTC, mariajgrimaldi commented on src/containers/ListView/messages.js
> +    defaultMessage: 'Problem Steps',
Didn't know that. Thanks.

2024-03-20 19:20 UTC, arbrandes commented
Before I do a proper review, do we have a thumbs-up from Product, for this one?

2024-03-21 14:04 UTC, johnvente commented
Hi @arbrandes this is the thumbs-up from Product: https://github.com/openedx/edx-ora2/issues/1974

2024-05-01 21:06 UTC, mphilbrick211 commented
Hi @arbrandes just checking in on this!

2024-05-10 21:48 UTC, BryanttV commented
We have just updated the PR including the necessary changes to consume the [API in edx-ora2](https://github.com/openedx/edx-ora2/pull/2101). There is still a need to rebase with master, resolve conflicts, and correct the unit tests.

2024-05-15 13:31 UTC, arbrandes commented
@BryanttV, mind tackling that rebase so I can test this on master?

2024-05-17 20:10 UTC, BryanttV commented
Hi @arbrandes, I already rebased with master, you can test now. I'm not sure why the tests are failing, but we will spend some time trying to fix it internally. Thanks!

2024-07-30 20:43 UTC, mphilbrick211 commented
@BryanttV @arbrandes just checking in on this!

2024-09-23 15:02 UTC, mariajgrimaldi commented
Hello, @mphilbrick211. Thanks for the ping! We currently don't have enough capacity to continue this work, so it's best to close it until someone can pick it up again. Thanks for the patience :)

2024-09-23 15:02 UTC, closed without merging