fix: request error for empty user list responses
openedx/frontend-app-ora-grading pull request #291
Opened 2023-11-14 15:12 UTC by DmytroAlipov

### Description:

"An unexpected error occurred" if you try to get all responses when the users' list is empty:

1. Open ORA Grading:

![111](https://github.com/openedx/frontend-app-ora-grading/assets/98233552/7acd8882-13d8-451b-b6ec-6b9031d80c78)

2. In Search username fill in not existing student username:

![222](https://github.com/openedx/frontend-app-ora-grading/assets/98233552/93f0ad46-a5d8-473d-9afb-d3fba1459df0)

3. Click on **View all responses**:

![333](https://github.com/openedx/frontend-app-ora-grading/assets/98233552/89f631a8-a18d-4723-8cea-46a21e30e150)

**I suggest not sending a request if the users are not on the list.**

2023-11-14 15:12 UTC, openedx-webhooks commented
Thanks for the pull request, @DmytroAlipov! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-11-14 15:12 UTC, openedx-webhooks commented
Thanks for the pull request, @DmytroAlipov! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-11-14 18:24 UTC, mphilbrick211 commented
Hi @openedx/content-aurora! This is ready for review.

2024-03-20 19:31 UTC, arbrandes requested changes
While this solves the error message, it doesn't fix the problem completely: there's still no user feedback when the button is pressed with an empty list of results.

I believe a better fix would be to show a message in the ShowReview modal to the effect that no responses were selected.  Is this something you can take on?

2024-03-20 19:32 UTC, arbrandes commented
Or, for a possibly an easier fix, to grey out the `View all responses` button when none are showing.

2024-03-20 20:20 UTC, DmytroAlipov commented
Hi, @arbrandes!
I think an inactive (gray) button would be a good option and, at first glance, not a difficult task. I'll try to implement this.

2024-03-21 09:32 UTC, DmytroAlipov commented
@arbrandes I made the button inactive. Now you can't send a request if the list is empty.

<img width="2044" alt="screen_40" src="https://github.com/openedx/frontend-app-ora-grading/assets/98233552/1404cd7f-9b54-42af-9fe3-1fe4a0a58f96">

2024-03-22 16:30 UTC, arbrandes requested changes
Brilliant!  Not to be too picky, but do you mind adding a unit test for when the button should be disabled (and when it shouldn't)?

2024-03-22 17:15 UTC, DmytroAlipov commented
@arbrandes Now this is implemented as a snapshot (button enabled). If I make a test also based on a snapshot with only the button disabled, will such a test be ok?

2024-03-23 14:59 UTC, DmytroAlipov commented
@arbrandes I added a test😉

2024-04-03 18:24 UTC, arbrandes approved these changes
Alright, looks good, thank you for bearing with me!

2024-04-03 18:25 UTC, merged

2024-04-03 18:25 UTC, openedx-webhooks commented
@DmytroAlipov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/291&entry.1484655318=https://github.com/DmytroAlipov&entry.752974735=2023-11-14+15:12&entry.1917517419=2024-04-03+18:25&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->