feat: Add header styles inclusion
openedx/frontend-app-ora-grading pull request #321
Opened 2024-03-14 11:13 UTC by Lunyachek

Header styles inclusion like it done in frontend-app-learning - https://github.com/openedx/frontend-app-learning/blob/master/src/index.scss#L7

It can be useful for example for the potential using for cookie banner

2024-03-14 11:13 UTC, openedx-webhooks commented
Thanks for the pull request, @Lunyachek!


This repository is currently maintained by `@codewithemad`.


Once you've gone through the following steps feel free to tag them in a comment and let them know that your changes are ready for engineering review.

<details><summary>:radio_button: Get product approval</summary>

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.
</details>

<details><summary>:radio_button: Provide context</summary>

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads
</details>





<details><summary>:radio_button: Get a green build</summary>

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.
</details><details>


---

<details><summary>Where can I find more information?</summary>

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)
</details>

<details><summary>When can I expect my changes to be merged?</summary>

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*
</details>
<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-03-20 20:29 UTC, arbrandes requested changes, later dismissed
It makes sense, but I wonder what the impact is, visually.  I can find some header-specific CSS [here](https://github.com/openedx/frontend-app-ora-grading/blob/master/src/App.scss#L23), and I'm worried that bringing in the default styles will break them, somehow.

Can we get before-after screenshots?

2024-05-01 21:10 UTC, mphilbrick211 commented
Hi @Lunyachek! Just following up on this.

2024-05-01 21:10 UTC, openedx-webhooks commented
@Lunyachek Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/321&entry.1484655318=https://github.com/Lunyachek&entry.752974735=2024-03-14+11:13&entry.1917517419=2024-05-01+21:10&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->

2024-05-01 21:10 UTC, mphilbrick211 commented
Sorry... didn't mean to close!

2024-05-30 09:45 UTC, Lunyachek commented
Sorry for delay. @arbrandes I added screenshots

Before
<img width="1840" alt="Снимок экрана 2024-05-30 в 11 23 35" src="https://github.com/openedx/frontend-app-ora-grading/assets/19806032/43e36a6b-4387-4bfa-98b8-3e724871116e">

and after
<img width="1840" alt="Снимок экрана 2024-05-30 в 11 23 07" src="https://github.com/openedx/frontend-app-ora-grading/assets/19806032/a267fce0-da1e-45a2-b1a2-027ca9f3a14d">

The included header styles don't affect the styles described in ORA MFE

2024-07-30 20:46 UTC, mphilbrick211 commented
@arbrandes - flagging the above!

2024-09-11 09:49 UTC, Lunyachek commented
@arbrandes Hello! Friendly ping on this

2024-12-09 21:56 UTC, mphilbrick211 commented
@Lunyachek @CodeWithEmad - just checking in here to see if this is going to proceed? It looks like Adolfo hasn't had a chance to take a look.

2024-12-18 08:05 UTC, CodeWithEmad approved these changes

2024-12-18 08:14 UTC, CodeWithEmad commented
@Lunyachek Can you kindly rebase this with master?

2025-02-20 11:32 UTC, Lunyachek commented
@CodeWithEmad Rebase done!

2025-02-20 14:49 UTC, merged

2025-02-20 14:49 UTC, CodeWithEmad commented
Thanks, @Lunyachek