feat: Mathjax for formules formatting
openedx/frontend-app-ora-grading pull request #339
Opened 2024-06-12 16:29 UTC by vladislavkeblysh

### Description
- Add Mathjax lib for formatting formules

#### Related Pull Requests

- master - https://github.com/openedx/frontend-app-ora-grading/pull/336
- quince.master - https://github.com/openedx/frontend-app-ora-grading/pull/337
- redwood.master - https://github.com/openedx/frontend-app-ora-grading/pull/338

#### Screenshots before:
| <img width="980" alt="image" src="https://github.com/openedx/frontend-app-ora-grading/assets/138868841/66b4d97c-c7f9-4eca-8564-563503d87be7"> |
|---|

#### Screenshots after:
| <img width="980" alt="image" src="https://github.com/openedx/frontend-app-ora-grading/assets/138868841/f639ecad-3e95-4ca9-a6b1-6464df778ba0"> |
|---|

2024-06-12 16:29 UTC, openedx-webhooks commented
Thanks for the pull request, @vladislavkeblysh! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-06-13 14:24 UTC, vladislavkeblysh commented
Has problem with CI checker. Tryed to use node version 18.19 and npm 9/10. Problems still unsolved

2024-06-13 16:34 UTC, brian-smith-tcril commented
@vladislavkeblysh I tried pulling this locally and running
```sh
nvm use
npm ci
```
and I was able to reproduce the error CI is showing. I then ran
```sh
npm install
```
and then
```sh
npm ci
```
and the error was no longer there.

This makes me think that CI should make it past the current error if you run
```sh
npm install
```
and check in the updated `package-lock.json`

2024-06-14 09:09 UTC, vladislavkeblysh commented
@brian-smith-tcril I did the same thing, but the problem persists.

2024-06-14 14:18 UTC, brian-smith-tcril commented
@vladislavkeblysh what do you see locally when running
```sh
rm -rf node_modules
nvm use
npm ci
```

2024-06-19 11:54 UTC, arbrandes commented
We'll probably want product review, here.  Mathjax support across the platform is somewhat inconsistent, and we'll likely want to figure out a strategy going forward.

2024-12-10 19:50 UTC, mphilbrick211 commented
@jmakowski1123 - is there a product roadmap ticket for this?

2025-02-25 17:42 UTC, jmakowski1123 commented
This one needs a roadmap ticket and product review.

2025-03-03 17:21 UTC, mphilbrick211 commented
> This one needs a roadmap ticket and product review.

Thanks @jmakowski1123 - can you link to the roadmap ticket here (once it's live)?

2025-09-23 10:26 UTC, vladislavkeblysh commented
@arbrandes @brian-smith-tcril ready to review

2025-09-23 13:24 UTC, mphilbrick211 commented
Per @jmakowski1123 this does not need to go through Prod review. All set to merge after review.

2025-09-23 15:21 UTC, arbrandes requested changes
The code looks alright, but I'm concerned that this uses a completely different method to load MathJax than the current pattern in the codebase, which is to load MathJax 2.7.5 directly from a CDN.  ([edx-platform example](https://github.com/openedx/edx-platform/blob/master/common/templates/xblock_v2/xblock_iframe.html#L190-L190), [frontend example](https://github.com/openedx/frontend-app-ora/blob/master/src/utils/renderMathJax.js#L67-L67)).

I also don't see an attempt to replicate the MathJax configuration used elsewhere ([edx-platform example](https://github.com/openedx/edx-platform/blob/master/common/templates/mathjax_include.html#L40-L57), [frontend example](https://github.com/openedx/frontend-app-ora/blob/master/src/utils/renderMathJax.js#L43-L57)).  What makes this worse is that apparently there is no single configuration pattern in the codebase.  Has an evaluation been made to check that what configuration is actually necessary?

In other words: how likely is it that loading MathJax via `better-react-mathjax` will result in a rendering that is different than what the author intended?

2025-10-15 07:14 UTC, vladislavkeblysh commented
@arbrandes Thanks for pointing that out. I’ve checked both MathJax configurations you referenced.

I’ve updated the configuration in better-react-mathjax to match them:
	•	MathJax v2.7.5 (same as current CDN load)
	•	inlineMath and displayMath definitions from both templates
	•	processEscapes: true and SVG max-width fixes
	•	messageStyle: 'none' and automatic linebreaks for all output types

2025-12-19 18:14 UTC, mphilbrick211 commented
Hi @vladislavkeblysh! Is this still in progress?

2026-01-22 22:42 UTC, mphilbrick211 commented
Checking in on this, @arbrandes @vladislavkeblysh

2026-01-23 14:08 UTC, arbrandes commented
I have one last request for @vladislavkeblysh besides getting CI to pass: can you please capture a couple of screenshots comparing how this PR renders Mathjax versus the LMS and CMS for the same block?

2026-02-25 20:17 UTC, mphilbrick211 commented
> I have one last request for @vladislavkeblysh besides getting CI to pass: can you please capture a couple of screenshots comparing how this PR renders Mathjax versus the LMS and CMS for the same block?

Flagging this for you, @vladislavkeblysh!

2026-04-01 15:19 UTC, vladislavkeblysh commented
@arbrandes Hi, sorry for the long waiting

PR is updated:

- Fixed CI and updated MathJax config from v2 format (tex2jax, CommonHTML) to v3 (tex, chtml, svg) — the old config was incompatible with better-react-mathjax which loads MathJax 3. 
- Resolved merge conflicts with master. 
- Added comparison screenshots.

<img width="1847" height="741" alt="lms-student-view-mathjax" src="https://github.com/user-attachments/assets/e1207970-2908-4f64-839c-d1205f200936" />
<img width="2056" height="1150" alt="ora-grading-mfe-mathjax" src="https://github.com/user-attachments/assets/6c811733-9dcc-4e6a-af01-ec41ccb3b63f" />

2026-04-02 10:34 UTC, arbrandes approved these changes
Alright, I'm convinced.  Wherever there's MathJax under React, we should use this pattern.

2026-04-02 10:37 UTC, merged