feat: make notification banner dismissible
openedx/frontend-app-ora-grading pull request #362
Opened 2024-10-02 09:33 UTC by asadali145

## Description

The notification banner is always visible and cannot be dismissed. Also, if ACCOUNT_SETTINGS_URL is not set, it redirects to `<ora_grading>/notifications`, which is not a valid URL.

This PR makes the banner dismissible and displays text instead of a link when the ACCOUNT_SETTINGS_URL is not set.

## Screenshots

Before:

<img width="1739" alt="Screenshot 2024-10-02 at 2 28 24 PM" src="https://github.com/user-attachments/assets/00ff77c2-454c-4d85-8f53-bf9d206028ef">

After (If ACCOUNT_SETTINGS_URL is not set):

<img width="1739" alt="Screenshot 2024-10-02 at 2 29 01 PM" src="https://github.com/user-attachments/assets/6dee022d-a243-4a82-bedd-a2bb8c14d3f4">

After (If ACCOUNT_SETTINGS_URL is set):

<img width="1739" alt="Screenshot 2024-10-02 at 2 32 25 PM" src="https://github.com/user-attachments/assets/3ea91a76-131b-4f4b-9167-ee0445c63192">

2024-10-02 09:33 UTC, openedx-webhooks commented
Thanks for the pull request, @asadali145!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/openedx-unmaintained`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-10-09 11:48 UTC, awais-ansari requested changes

2024-10-09 11:48 UTC, awais-ansari commented on src/containers/NotificationsBanner/index.jsx
> +import _ from 'lodash';
import specific function instead of whole library.
`import {isEmpty} from 'lodash';`

2024-10-14 09:10 UTC, awais-ansari approved these changes

2024-10-17 14:30 UTC, brian-smith-tcril commented on src/containers/NotificationsBanner/index.jsx
> +          <FormattedMessage {...messages.notificationsBannerLinkMessage} />
It feels a little odd to me to have the `notificationsBannerLinkMessage` only be a link *sometimes*. I think it makes more sense to have 2 (technically 3) fully independent strings:
* `infoMessage` + `notificationsBannerLinkMessage` when we have an `ACCOUNT_SETTINGS_URL`
* Something else entirely when we do not have an `ACCOUNT_SETTINGS_URL`

Another option that may be simpler would just be renaming `notificationsBannerLinkMessage` to `notificationsBannerPreferencesCenterMessage`.

@sarina which option we choose feels a little like a product question to me. Should I tag someone to get a product opinion? If not I'd be happy to merge this with the rename to `notificationsBannerPreferencesCenterMessage` as that feels like a smaller change.

2024-10-17 14:47 UTC, sarina commented on src/containers/NotificationsBanner/index.jsx
> +          <FormattedMessage {...messages.notificationsBannerLinkMessage} />
well for i18n you should embed the URL within the phrase, not concat them, if that's what you're suggesting.

I think the easiest is to rename the message. I think there's a separate DEPR for removing this banner altogether.

2024-10-17 14:53 UTC, brian-smith-tcril commented on src/containers/NotificationsBanner/index.jsx
> +          <FormattedMessage {...messages.notificationsBannerLinkMessage} />
Sounds good to me!

@asadali145 - if `notificationsBannerLinkMessage` is renamed to `notificationsBannerPreferencesCenterMessage` this PR will look ready to merge to me!

2024-10-18 12:02 UTC, asadali145 commented on src/containers/NotificationsBanner/index.jsx
> +          <FormattedMessage {...messages.notificationsBannerLinkMessage} />
@brian-smith-tcril thanks for the review. PR is ready.

2024-10-23 17:21 UTC, brian-smith-tcril commented on src/containers/NotificationsBanner/index.jsx
> +import { isEmpty } from 'lodash';
Do we know all the possible "empty" values that `getConfig().ACCOUNT_SETTINGS_URL` returns? I'd prefer we avoid adding a `lodash` dependency to this file if possible.

2024-10-28 10:55 UTC, asadali145 commented on src/containers/NotificationsBanner/index.jsx
> +import { isEmpty } from 'lodash';
Yeah, I have replaced the lodash check with the values check. Could you please have another look?

Also, Just a reminder that we have another CTA banner removal PR that's pending for review https://github.com/openedx/frontend-app-ora-grading/pull/347.

2024-11-01 16:15 UTC, brian-smith-tcril approved these changes
Thank you for updating the logic not not require `lodash`!

2024-11-04 14:13 UTC, asadali145 commented
@brian-smith-tcril Could you please merge this?

2024-11-04 16:40 UTC, brian-smith-tcril commented
@asadali145 it looks like this PR needs a rebase as branch protections require it not be out-of-date with the base branch. Would you be able to update it? Once that's done I can hit the merge button.

2024-11-04 16:50 UTC, asadali145 commented
@brian-smith-tcril Thank you, I just rebased and the checks are passing.

2024-11-04 17:22 UTC, merged