feat: add file renderer that support common error handling and loading banner
openedx/frontend-app-ora-grading pull request #42
Opened 2022-01-10 17:22 UTC by leangseu-edx

![Screen Shot 2022-01-10 at 12 22 01 PM](https://user-images.githubusercontent.com/83240113/148810026-26467283-57df-4cef-a6b3-d4d5c214a700.png)

2022-01-11 16:24 UTC, muselesscreator commented on src/components/FilePreview/Banners/ErrorBanner.jsx
> +});
I feel like we should put this shape in a top-level util.  I have had to add it elsewhere as well.

2022-01-11 16:27 UTC, muselesscreator commented on src/components/FilePreview/Banners/ErrorBanner.test.jsx
> +      actions.forEach(action => expect(action.type).toEqual('Button'));
plz add a test verifying the other button props (could be in this same test).
At minimum the onClick, but message would also make sense.  This is a reformatting action, so I would like it to be captured.

2022-01-11 16:28 UTC, muselesscreator commented on src/components/FilePreview/Banners/ErrorBanner.test.jsx
> +        onClick: jest.fn().mockName('test 1 on click'),
I would rename these to `props.action1.onClick` for clearer tying in the snapshot.

2022-01-11 16:29 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/ImageRenderer.test.jsx
> +    onError: jest.fn().mockName('onError'),
prefer `props.onError`

2022-01-11 16:30 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/PDFRenderer.jsx
> +      case 'MissingPDFException':
This feels overly verbose unless we are expecting later addition of other error states... are we?

2022-01-11 16:30 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/PDFRenderer.test.jsx
> +    onError: jest.fn().mockName('onError'),
prefer `props.onError`

2022-01-11 16:34 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
I would like this to be a thunkAction in the download module.

2022-01-11 17:28 UTC, leangseu-edx commented on src/components/FilePreview/BaseRenderers/PDFRenderer.jsx
> +      case 'MissingPDFException':
There is 2 state of errors I can produce so far. The other one has a bad name. It was normal casing of unknown error. It is a bit inconsistent from the library to be honest.

All I am trying to do here is to send back status code. Assuming the FileRenderer will figure out the rest.

2022-01-11 17:29 UTC, leangseu-edx commented on src/components/FilePreview/Banners/ErrorBanner.jsx
> +});
Fair, I can definitely clean up on a different commit. We know there are more files using this that isn't part of this commit.

2022-01-11 17:30 UTC, leangseu-edx commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
The problem with that is that we are not downloading all of the files. Example, image. It are just putting url in img tag. thunkAction would make all of this inconsistent.

2022-01-11 17:33 UTC, leangseu-edx commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
I don't like connecting redux to anything within components folder. I always treat it as an independent components from a different library.

2022-01-11 19:47 UTC, muselesscreator commented on src/containers/ResponseDisplay/PreviewDisplay.test.jsx
> +        new Array(cards.length).fill(0).forEach((_, index) => {
why not cards.forEach?

2022-01-11 19:49 UTC, muselesscreator commented on src/containers/ResponseDisplay/PreviewDisplay.test.jsx
>        test('files exited for props', () => {
This snapshot needs a better name...

2022-01-11 19:56 UTC, muselesscreator commented on src/containers/ResponseDisplay/PreviewDisplay.test.jsx
>        test('files exited for props', () => {
In fact, both snapshot names are bad.  this one is confusing, and the other is just wrong.

2022-01-11 19:58 UTC, muselesscreator commented on src/containers/ResponseDisplay/PreviewDisplay.test.jsx
> +  isSupported: (file) => jest.requireActual('components/FilePreview').isSupported(file),
```suggestion
  isSupported: jest.requireActual('components/FilePreview').isSupported,
```

2022-01-11 19:59 UTC, muselesscreator commented on src/containers/ResponseDisplay/PreviewDisplay.test.jsx
> +      FileTypes.txt,
I feel like this should just be importing these, rather than re-defining them here, as there isn't code in the connected file to verify them against.

2022-01-11 20:00 UTC, muselesscreator commented on src/components/FilePreview/messages.js
> +    description: 'Try to refetch the file',
This description should be for the translator of what/where the message is, not alt-text.

2022-01-11 20:00 UTC, muselesscreator commented on src/components/FilePreview/messages.js
> +    description: 'Try to refetch the file',
(these)

2022-01-11 20:03 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.test.jsx
> +          expect(el.instance().render()).toMatchSnapshot();
need to mock out methods for these

2022-01-11 20:06 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.test.jsx
> +          expect(renderer.prop('url')).toEqual(file.downloadUrl);
prefer to avoid strings for things like this where possible:
```
const { url, fileName } = renderer.props();
expect(url).toEqual(file.downloadUrl);
expect(fileName).toEqual(file.name);
```

2022-01-11 20:06 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.test.jsx
> +        it(`${fileType} renderer must have onError and onSuccess props`, () => {
```suggestion
        test(`${fileType} renderer must have onError and onSuccess props`, () => {
```

2022-01-11 20:07 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.test.jsx
> +        // the manual process for this is prefer.
more details on this comment plz

2022-01-11 20:09 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +          <ErrorBanner {...this.state.error} />
I would only store the error in state, and the rest in a class prop that we add in here

2022-01-11 20:14 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +          <ErrorBanner {...this.state.error} />
<ErrorBanner {...ERROR_STATUSES[this.state.error]} actions={[this.retryAction]} />

2022-01-11 20:14 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +    this.setState({
```
onError(status) {
  this.setState({
    error: ERROR_STATUSES[status] ? status : 500,
    isLoading: false,
  })
}

get retryAction() {
  return {
    id: 'retry',
    onClick: this.resetState,
    message: messages.retryButton,
  };
}
```

2022-01-11 20:15 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.test.jsx
> +    onError: jest.fn().mockName('onError'),
`this.props.onError`

2022-01-11 20:16 UTC, muselesscreator requested changes
Some clean-up requests

2022-01-11 20:17 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
Then we can have it in a comms dir.  I heavily prefer avoiding having network actions (especially ones drawing from our utils) managed directly within the context of a component.

2022-01-11 20:26 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
```
const getTextFile = ({ url, onSuccess, onError }) => get(url)
  .then(({ data }) => onSuccess(data))
  .catch(({ response }) => onError(response.status));

// in component
  //should be a class method...
  const handleSuccess = (data) => {
    onSuccess();
    setContent(data);
  }
  useMemo(() => getTextFile({ url, onError, onSuccess: handleSuccess }));
  
// or more cleanly in a class component:
class TXTRenderer extends Component {
  constructor(props) {
    super(props);
    this.state = { content: '' };
    this.onSuccess = this.onSuccess.bind(this);
  }
  componentDidMount() {
    getTextFile({
      url: this.props.url,
      onError: this.props.onError,
      onSuccess: this.onSuccess,
    });
  }
  onSuccess(content) {
    this.props.onSuccess();
    this.setState({ content });
  }
  render() {
    ...
  }
}

2022-01-12 14:56 UTC, leangseu-edx commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
Would it be better if I just use axios and assume no auth require?

2022-01-12 19:58 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
also that, yes

2022-01-12 19:59 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/__snapshots__/TXTRenderer.test.jsx.snap
> +exports[`TXY Renderer Component snapshot 1`] = `
```suggestion
exports[`TXT Renderer Component snapshot 1`] = `
```

2022-01-12 19:59 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/PDFRenderer.test.jsx
> +  props.onError = jest.fn().mockName('onError');
```suggestion
  props.onError = jest.fn().mockName('this.props.onError');
```

2022-01-12 19:59 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/PDFRenderer.test.jsx
> +  props.onSuccess = jest.fn().mockName('onSuccess');
```suggestion
  props.onSuccess = jest.fn().mockName('this.props.onSuccess');
```

2022-01-12 19:59 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/ImageRenderer.test.jsx
> +  props.onError = jest.fn().mockName('onError');
```suggestion
  props.onError = jest.fn().mockName('this.props.onError');
```

2022-01-12 19:59 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/ImageRenderer.test.jsx
> +  props.onSuccess = jest.fn().mockName('onSuccess');
```suggestion
  props.onSuccess = jest.fn().mockName('this.props.onSuccess');
```

2022-01-12 20:00 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.test.jsx
> +describe('TXY Renderer Component', () => {
```suggestion
describe('TXT Renderer Component', () => {
```

2022-01-12 20:00 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.test.jsx
> +  props.onError = jest.fn().mockName('onError');
```suggestion
  props.onError = jest.fn().mockName('this.props.onError');
```

2022-01-12 20:00 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.test.jsx
> +  props.onSuccess = jest.fn().mockName('onSuccess');
```suggestion
  props.onSuccess = jest.fn().mockName('this.props.onSuccess');
```

2022-01-13 19:35 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +  resetState = () => {
This needs to be a class method so it can be mocked in the snapshot

2022-01-13 19:36 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +  get getError() {
```suggestion
  get error() {
```

2022-01-13 19:36 UTC, muselesscreator commented on src/components/FilePreview/FileRenderer.jsx
> +  get getError() {
is a getter, so why include `get` in name?

2022-01-13 19:39 UTC, muselesscreator commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
I'm not going to make a big fuss about it for this PR, but I am going to open a ticket to move the download functionality (will include this and the zip download methods) in a new data folder `data/files`

2022-01-13 20:27 UTC, leangseu-edx commented on src/components/FilePreview/BaseRenderers/TXTRenderer.jsx
> +    get(url)
My hot takes for this is that it should be consistence with other renderers. I am trying to make it close to PDFRenderers etc... If we are going to make download part of redux, it should be consistence for all of them. We can make FileRenderer do the download before delegating it to the BaseRenderers.

2022-01-19 17:34 UTC, muselesscreator approved these changes
LGTM

2022-01-19 17:34 UTC, merged