fix: scroll enable on smaller screen
openedx/frontend-app-ora-grading pull request #51
Opened 2022-01-26 13:33 UTC by leangseu-edx

TLDR; make sure the response display scrollable on small screen

2022-01-26 21:46 UTC, mattcarter commented
@leangseu-edx can you include screenshots please

2022-01-27 02:29 UTC, leangseu-edx commented
> @leangseu-edx can you include screenshots please

I made a video, not sure it would be a clear presentation.

2022-02-02 15:29 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +      test(`feedback is configure to ${requirement}`, () => {
```suggestion
      test(`feedback is configured to ${requirement}`, () => {
```

2022-02-02 15:29 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +  get commentMessage() {
this get logic needs a test.

2022-02-02 15:31 UTC, muselesscreator requested changes
looks great! 1 minor spelling nit and 1 missing new test.

2022-02-02 20:07 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +      el.setProps({ config: feedbackRequirement.optional });
this should be a describe, and it should test the conditional inclusion of the 'optional' message as well as `comments` vs `addComments`

2022-02-08 15:30 UTC, muselesscreator approved these changes
LGTM

2022-02-08 15:33 UTC, merged