feat: override filter status component
openedx/frontend-app-ora-grading pull request #67
Opened 2022-02-16 19:46 UTC by leangseu-edx

[AU-534](https://openedx.atlassian.net/browse/AU-534)

![filter](https://user-images.githubusercontent.com/83240113/154343556-c867b640-7606-4db3-82fb-0cae7a4c8383.png)

2022-02-22 16:16 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.jsx
> +        onClick={() => setAllFilters([])}
this needs to be mock-able.

2022-02-22 16:17 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.jsx
> +  className: null,
because you are passing this, and it shows up in the snapshot, I would pass an empty string

2022-02-22 16:18 UTC, muselesscreator requested changes
a couple of testing concerns

2022-02-25 00:54 UTC, leangseu-edx commented on src/containers/ListView/FilterStatusComponent.jsx
> +        onClick={() => setAllFilters([])}
`setAllFilters` is a function that came from the Context, I am not sure how to mock this properly even with class component. Please look at current way I mock it.

2022-02-25 00:57 UTC, leangseu-edx commented on src/containers/ListView/FilterStatusComponent.test.jsx
> +      jest.spyOn(React, 'useCallback').mockImplementationOnce(() => jest.fn().mockName('clearFilters'));
This has to be in the same order of `useCallback` being written. It is not the most ideal but it get the job done.

2022-03-14 15:16 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.jsx
> +const FilterStatusComponent = ({
suggestion:
define hook method outside the component that grabs the datatable context and returns what is needed.
```
import * as module from './FilterStatusComponent';

const filterHooks = () => {
    const { state, setAllFilters, headers } = React.useContext(DataTableContext);
    if (!setAllFilters || !state.filters) {
      return {};
    }
    const clearFilters = React.useCallback(() => setAllFilters([]), []);
    const headerMap = headers.reduce((obj, cur) => ({ ...obj, [cur.id]: cur.Header }), {});
    const filterNames = state.filters.map(filter => headerMap[filter.id]);
    return { clearFilters, filterNames };
};

const FilterStatusComponents = ({ ... }) => {
  const { clearFilters, filterNames } = module.filterHooks();
  if (!clearFilters {
    return null;
  }
  ...
```

2022-03-14 15:16 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.jsx
> +const FilterStatusComponent = ({
then, you can mock the hook method before it goes into the component to verify the 2 pieces you want in the component test, but you can also mock out useCallback to return the callback without calling it, to verify the state before and after it is called (verifying that setAllFilters is called with empty list)

2022-03-15 15:41 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.test.jsx
> +      expect(mockSetAllFilters).toHaveBeenCalledTimes(1);
The goal with this test was to verify what the callback actually does.
so, useCallback should be taking a callback and set of memoization pre-reqs, and returning them.  Then we test that the cb actually calls the setAllFilters passed in the contextProps with an empty list.

2022-03-15 15:44 UTC, muselesscreator commented on src/containers/ListView/FilterStatusComponent.test.jsx
> +      jest.spyOn(React, 'useCallback').mockImplementationOnce(() => mockSetAllFilters);
```suggestion
      jest.spyOn(React, 'useCallback').mockImplementationOnce((cb, prereqs) => ([cb, prereqs]));
```

2022-03-15 15:58 UTC, muselesscreator approved these changes
Have some testing issues, but I will address those in a follow-on PR.  Hook components should be unit-tested in the same way we test class components: verify behavior, and then verify linkage in snapshots, not by simulating click behavior and checking outcomes.

2022-03-15 16:04 UTC, merged