Demo flag
openedx/frontend-app-ora-grading pull request #89
Opened 2022-04-01 05:13 UTC by muselesscreator

Sets the frontend to load the "is this the demo version" flag from initialize api call.
Also updates the on-close behavior of the review modal to check if there are ANY active grades to display the modal, and dispatches a new (mocked) batchUnlock api method.

2022-04-04 17:04 UTC, leangseu-edx commented on src/containers/ListView/__snapshots__/EmptySubmission.test.jsx.snap
> +    src="icon/mock/path"
where is this coming from?

2022-04-04 17:07 UTC, leangseu-edx commented on src/data/redux/thunkActions/app.test.js
> +      test('loads isEnabled, oraMetadata, courseMetadata and list data', () => {
👍

2022-04-04 17:10 UTC, leangseu-edx commented on src/data/redux/thunkActions/requests.js
> + * Tracked setLock api method.  tracked to the `setLock` request key.
🏆

2022-04-04 17:10 UTC, leangseu-edx commented on src/data/services/lms/api.js
> +  console.log({ batchUnlockSubmissions: submissionUUIDs });
to be remove

2022-04-04 17:13 UTC, leangseu-edx commented on src/utils/keyStore.js
> +export default keyStore;
This file isn't being use.

2022-04-04 17:13 UTC, leangseu-edx requested changes
Look good. Just remove the debris.

2022-04-05 14:37 UTC, muselesscreator commented on src/data/services/lms/api.js
> +  console.log({ batchUnlockSubmissions: submissionUUIDs });
leaving this until we have the actual API hook connected as the interim way of verifying the action worked.

2022-04-05 14:40 UTC, muselesscreator commented on src/containers/ListView/__snapshots__/EmptySubmission.test.jsx.snap
> +    src="icon/mock/path"
not sure where specifically, but I should update with intentional mock.

2022-04-05 14:43 UTC, muselesscreator commented on src/utils/keyStore.js
> +export default keyStore;
This was introduced in the TnL stuff and I want to start using it, especially for places where we are spying on things

2022-04-05 14:47 UTC, muselesscreator commented on src/utils/keyStore.js
> +export default keyStore;
added because I intend to use soon

2022-04-05 19:11 UTC, merged