Rubric feedback
openedx/frontend-app-ora-grading pull request #9
Opened 2021-10-05 13:46 UTC by leangseu-edx

- Update RubricFeedback component to include title and InfoPopover.
- Update RubricConfig to include feedbackPrompt and feedbackDefaultText
Ticket: [AU-339](https://openedx.atlassian.net/browse/AU-339)

<img width="1096" alt="Screen Shot 2021-10-04 at 4 24 33 PM" src="https://user-images.githubusercontent.com/83240113/136034974-72f1fd17-7cc5-46a7-97a9-8ea91fb7f6a4.png">

<img width="1099" alt="Screen Shot 2021-10-04 at 4 24 39 PM" src="https://user-images.githubusercontent.com/83240113/136034990-73cc11ac-da5d-4879-9d84-5c96628df8e8.png">

2021-10-05 15:42 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +              : <GradedCriterion orderNum={orderNum} />
This seems to have removed the ReviewCriterion, which is for ungraded entries.

2021-10-05 15:43 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +      </Form.Group> : <Form.Text className="feedback-text">{value}</Form.Text>
This cannot be grouped like this.   Please put the parentheses back.

2021-10-05 15:45 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +          floatingLabel={feedbackDefaultText}
This should be `{isGrading ? 'Add comments' : 'Comments'}`
feedbackDefaultText is not used.

2021-10-05 15:45 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +      </Form.Group> : <Form.Text className="feedback-text">{value}</Form.Text>
also, this should just be included in the above render, as the design is to show a disabled input with updated floating label.

2021-10-06 18:55 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +    if ((config === feedbackRequirement.disabled) || !(isGrading || value)) {
I don't think we should be hiding empty feedback for non-grading views.  If comments are configured, the field should be shown.  (empty string counts as false-y)

2021-10-06 18:56 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +            mapped = mapStateToProps(props, {
would rather this were a new testState object

2021-10-06 18:58 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +            rubricCriterionConfig: jest.fn(({ config }) => ({ ...config })),
({ config }) => ({ rubricCriterionConfig: config })

If you don't include the key name you aren't verifying the specific selector.

2021-10-06 18:58 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +                criterionGradeData: jest.fn(({ data }) => ({ ...data })),
^

2021-10-06 18:59 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +    __esModule: true,
don't actually need to mock these

2021-10-06 18:59 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +            mapped = mapStateToProps(props, {
Same comment as previous file.   Please keep the convention of testing mapStateToProps against a "state" (testState) component.

2021-10-06 19:07 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +    return <Form.Group>
Please put the parenthesis back.  This formatting is much harder to read.

2021-10-06 19:07 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +    if (config === feedbackRequirement.disabled || !(isGrading || value)) {
As with criterion feedback, if it is configured, it should show up, regardless of grading status/value.

2021-10-06 19:10 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +    OverlayTrigger: () => 'OverlayTrigger',
JS indentation is 2-spaces

2021-10-06 19:11 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +    Icon: () => 'Icon',
Because of how this is passed into the component render, you should use:
```Icon: jest.fn().mockName('Icon')```

2021-10-06 19:11 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +    InfoOutline: () => 'InfoOutline'
Because of how this is passed in, you should use:
```InfoOutline: jest.fn().mockName('icons.InfoOutline')

2021-10-06 19:12 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +    const child = <div>Children component</div>
parenthesis and semicolon

2021-10-06 19:13 UTC, muselesscreator commented on src/components/__snapshots__/InfoPopover.test.jsx.snap
> +    iconAs={[Function]}
these should be named (code suggestions in linked test)

2021-10-06 19:13 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +      floatingLabel="Comments"
label should be "Add Comments" if grading, and "Comments" if not grading

2021-10-06 19:14 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +    Form: {
2-space indentation

2021-10-06 19:14 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +    __esModule: true,
don't need to mock the actions.

2021-10-06 19:15 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +            isGrading: jest.fn(({ isGrading }) => ({ isGrading })),
output should include unique key:
```(...state) => ({ isGrading: args })```

2021-10-06 19:15 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.test.jsx
> +        setValue: jest.fn().mockName('this.props.setValue')
not a big issue here, but I tend to assign function props in beforeEach, as that way they are fresh for each test, in case tests involve calling/checking the mock.

2021-10-06 19:21 UTC, muselesscreator commented on src/containers/CriterionContainer/ReviewCriterion.jsx
> +export class ReviewCriterion extends React.Component {
This component should not have changed, as this is still the designed behavior.  Radio buttons are only for Graded or isGrading components.
We had discussed naming these `ReviewCriterion` and `RadioCriterion` for this reason.

2021-10-06 19:23 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +            expect(mapped.data).toEqual(selectors.grading.selected.criterionGradeData(props));
these long lines need to be broken up.

2021-10-06 19:25 UTC, muselesscreator commented on src/containers/CriterionContainer/GradingCriterion.test.jsx
> +        expect(
Need to mock onChange so it is named in the snapshot.

2021-10-06 19:25 UTC, muselesscreator commented on src/containers/CriterionContainer/__snapshots__/GradingCriterion.test.jsx.snap
> +      onChange={[Function]}
these functions should be named (need to mock on the snapshot)

2021-10-06 19:26 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
`from 'components/InfoPopover';`

2021-10-06 19:26 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
```suggestion
import InfoPopover from 'components/InfoPopover';
```

2021-10-06 19:27 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +jest.mock('components/InfoPopover', () => 'InfoPopover');
should be above the other mocks (absolute before relative)

2021-10-06 19:28 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +    __esModule: true,
don't need to mock actions

2021-10-06 19:28 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +    Form: {
2-space indentation

2021-10-06 19:28 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +            rubricCriterionConfig: jest.fn(({ config }) => ({ ...config })),
jest.fn((...args) => ({ rubricCriterionConfig: args }))

2021-10-06 19:29 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +    describe('component', () => {
If you are adding the option generation logic in here, that needs to be explicitly tested for content, not just w/ snapshots.

2021-10-06 19:29 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +            mapped = mapStateToProps(props, {
please follow the convention of testing against a state (testState) object.

2021-10-06 19:30 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +            expect(mapDispatchToProps.setFeedback).toEqual(actions.grading.setCriterionFeedback);
long lines need breaking up.

2021-10-06 19:30 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +            isGrading: jest.fn(({ isGrading }) => ({ isGrading })),
same comment as with other selectors mocks

2021-10-06 19:30 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +    __esModule: true,
not needed

2021-10-06 19:31 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +    Form: {
2-space indentation

2021-10-06 19:31 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +            mapped = mapStateToProps(props, {
same comment about testing against state object

2021-10-06 19:32 UTC, muselesscreator commented on src/containers/Rubric/__snapshots__/RubricFeedback.test.jsx.snap
> +    onChange={[Function]}
needs to be mocked on the snapshot with a name.

2021-10-06 19:34 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +import { InfoPopover } from '../../components/InfoPopover';
```suggestion
import InfoPopover from 'components/InfoPopover';
```

2021-10-06 19:35 UTC, muselesscreator commented on src/containers/Rubric/__snapshots__/RubricFeedback.test.jsx.snap
> +    <Component>
This mock isn't working because of how you imported InfoPopover in the component.  Comment on that file w/ suggested syntax.

2021-10-06 19:35 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +            expect(
need to mock onChange method.

2021-10-06 19:37 UTC, leangseu-edx commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +    if ((config === feedbackRequirement.disabled) || !(isGrading || value)) {
I will use `gradeStatus` instead. I think it would make more sense.

2021-10-06 19:45 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +    Card: {
This does not render well in snapshot.  I recommend using `card-body` className on the body component and just mocking the top-level component.

Alternatively, I would mock as a function:
```
jest.mock('@edx/paragon', () => {
  const Card = () => 'Card';
  Card.Body = () => 'Card.Body';
  const Button = () => 'Button';
  return { Button, Card };
}));
```
The latter option leaves you with a "<Component>" in the snapshot, where the former ties us to bootstrap-react's card implementation (which I believe is stable for quite the forseeable future).

Neither is perfect, either is fine. Whichever you go with should note the issues associated with that path.

2021-10-06 19:46 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +            isGrading: jest.fn(({ isGrading }) => ({ isGrading })),
same selector mock comments

2021-10-06 19:46 UTC, muselesscreator commented on src/containers/Rubric/__snapshots__/index.test.jsx.snap
> +<[object Object]
You need to check these for weird renders.  This is a symptom of `Card` and `Card.Body` being in the same component. Notes on that in the test file.

2021-10-06 19:47 UTC, muselesscreator commented on src/data/services/lms/fakeData/ora.js
> +  feedbackDefaultText: 'Default feedback',
we don't need this

2021-10-06 19:47 UTC, muselesscreator commented on src/data/selectors/app.js
> + export const rubricFeedbackDefaultText = createSelector(
we don't need this field.

2021-10-06 19:48 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +        placeholder={feedbackDefaultText}
no placeholder text.  We are not using feedbackDefaultText in this app.

2021-10-06 19:48 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +  feedbackDefaultText: selectors.app.rubricFeedbackDefaultText(state),
do not need

2021-10-06 19:53 UTC, muselesscreator requested changes
This runs well, but I have some issues in the code.

First and foremost, the branch needs be rebased against main branch, linted, and have its tests run so that the snapshots are up-to-date.

Beyond that, there are some paradigms I would like you to follow more closely.  Specifically:
* JSX should be wrapped in parentheses
* mocked selectors should take the form of `(...args) => ({ selectorName: args })`
  ^ this is to best make sure we are testing against the correct selector, and that we are grabbing state and any other passed arguments from ownProps.
* mapStateToProps should be tested against a `state`-like object, not props
* bound methods must be mocked and named on all snapshot tests

Finally, the `ReviewCriterion` and `GradingCriterion` component workflow here is not what we discussed.  We had discussed a `ReviewCriterion` that maintains the currently-design review UI, and a `RadioCriterion` component that encompasses graded and grading workflows.

2021-10-07 17:34 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +  Icon: () => 'Icon',
This needs to be mocked with a name, or just be a string

2021-10-07 17:35 UTC, muselesscreator commented on src/components/InfoPopover.test.jsx
> +  InfoOutline: jest.fn().mockName('icons.InfoOutline'),
this is good, but need to re-run the test to update snapshot.

2021-10-07 17:37 UTC, muselesscreator commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +      (!isGrading && gradeStatus === 'ungraded')
the feedback should still be displayed in that instance...  the only thing that should block the field showing up is if it is configured not to show up.  Having them show up in the ungraded version still communicates to the reviewer that comments on that criteria are part of the rubric.

2021-10-07 17:40 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +          <RadioCriterion orderNum={orderNum} isGrading={isGrading} />
This should still be either Radio or Review... why did the ReviewCriterion get deleted??

2021-10-07 17:41 UTC, muselesscreator commented on src/containers/CriterionContainer/ReviewCriterion.jsx
> -import React from 'react';
Why did this get deleted?

2021-10-07 17:42 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
this is still messing with your snapshot

2021-10-07 17:43 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +        criterionConfig: jest.fn(({ config }) => ({ ...config })),
still needs update

2021-10-07 17:43 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.jsx
> +      (!isGrading && gradeStatus === 'ungraded')
The field should be there if it is not disabled.

2021-10-07 17:46 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +      expect(el.find('.grading-rubric-footer').length).toEqual(1);
need to inspect the component for the options data

2021-10-07 17:46 UTC, muselesscreator commented on src/utils/StrictDict.js
> +  debugger
?

2021-10-07 17:51 UTC, muselesscreator requested changes
Looks much better, but still a couple of issues.
* Snapshots looking much better, but still a couple of issues.
* Selectors are better almost everywhere, but 1 file got missed.
* ReviewCriterion should still exist and show up for ungraded submissions
* Feedback fields should show up if not configured as disabled
* Need to inspect the InfoPopover contents in Rubric tests.

2021-10-07 18:00 UTC, leangseu-edx commented on src/containers/CriterionContainer/CriterionFeedback.jsx
> +      (!isGrading && gradeStatus === 'ungraded')
Does that mean feedback will always show even if the rubric hasn't been or going to touch?

2021-10-07 18:11 UTC, leangseu-edx commented on src/utils/StrictDict.js
> +  debugger
rebased and the error came from `StrictDict`

2021-10-07 18:20 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +      expect(rubricCritera.children(0).name()).toEqual('RadioCriterion');
plz add test for info popover contents including all the option info.

2021-10-08 13:11 UTC, jnlapierre approved these changes
LGTM, reviewed all feedback and follow up actions and ran the app and tests locally.

2021-10-08 14:39 UTC, muselesscreator commented on src/containers/CriterionContainer/RadioCriterion.test.jsx
> +          _rubricCriterionConfig: args,
```suggestion
          rubricCriterionConfig: args,
```

2021-10-08 14:40 UTC, muselesscreator commented on src/containers/CriterionContainer/ReviewCriterion.test.jsx
> +    const additionalArgs = { orderNum: props.orderNum };
nit: additionalArgs => ownProps (is the mapStateToProps standard)
```suggestion
    const ownProps = { orderNum: props.orderNum };
```

2021-10-08 14:40 UTC, muselesscreator commented on src/containers/CriterionContainer/ReviewCriterion.test.jsx
> +        selectors.app.rubric.criterionConfig(testState, additionalArgs),
```suggestion
        selectors.app.rubric.criterionConfig(testState, ownProps),
```

2021-10-08 14:40 UTC, muselesscreator commented on src/containers/CriterionContainer/ReviewCriterion.test.jsx
> +          additionalArgs,
```suggestion
          ownProps,
```

2021-10-08 14:41 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
```suggestion
import InfoPopover from 'components/InfoPopover';
```

2021-10-08 14:42 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +          {isGrading || gradeStatus === 'graded' ? (
plz import and check against gradeStatuses in `data/services/lms/constants`

2021-10-08 14:43 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +  gradeStatus: PropTypes.oneOf(['graded', 'ungraded']).isRequired,
plz load from gradeStatuses in `data/services/lms/constants`

2021-10-08 14:43 UTC, leangseu-edx commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
Arguably, for me it is easier for me to navigate when using `vscode`

2021-10-08 14:43 UTC, muselesscreator commented on src/containers/CriterionContainer/index.test.jsx
> +      optionsEl.forEach((optionEl, i) => {
:-)

2021-10-08 14:48 UTC, muselesscreator commented on src/containers/Rubric/RubricFeedback.test.jsx
> +    test('set value called on change', () => {
plz group the "render" tests, and wrap this one in a `describe('onChange method', () => {` block

2021-10-08 14:49 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +          _rubricCriteriaIndices: args,
```suggestion
          rubricCriteriaIndices: args,
```

2021-10-08 14:50 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +    test('is not grading', () => {
this is a description of the case, but not what you are testing.
```suggestion
    test('is not grading (no footer)', () => {
```

2021-10-08 14:50 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +    test('is grading', () => {
this is a state, not a test description.
```suggestion
    test('is grading (grading footer present)', () => {
```

2021-10-08 14:51 UTC, muselesscreator commented on src/containers/Rubric/index.test.jsx
> +    });
plz verify a criterion container is spawned per criterion.

2021-10-08 14:53 UTC, muselesscreator commented on src/containers/CriterionContainer/index.jsx
> +import InfoPopover from '../../components/InfoPopover';
that is a configuration issue then. Absolute referencing for top-level modules is important for mobility of code

2021-10-08 18:35 UTC, muselesscreator approved these changes
LGTM! :ship: :it:

2021-10-08 18:41 UTC, merged